spring.profiles.active=dev
spring.application.name=jewelry

# File Upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT Secrets and Expiration
veha.jwt.secret=9a70267a5818f8eab8d9b85cc49b3f9a70267a5818f8eab8d9b85cc49b3f9a
veha.jwt.expiration=86400000

# Mail Server Mock Config placeholder (Can be overridden in env)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=info@veha.com
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
