import { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: 101,
    name: 'Royal Diamond Ring',
    slug: 'royal-diamond-ring',
    description: 'A magnificent band of premium diamonds in a classic crown setting. Handcrafted in 22k yellow gold.',
    price: 45000,
    wasPrice: 59000,
    discountPercent: 23,
    featured: true,
    bestseller: true,
    stock: 15,
    svgRender: '/images/rings/rings_cover.jpeg',
    categoryName: 'Rings',
    categorySlug: 'rings'
  },
  {
    id: 105,
    name: 'Pearl Drop Earrings',
    slug: 'pearl-drop-earrings',
    description: 'Lustrous drop pearls suspended from polished 22k gold links. Designed for understated evening elegance.',
    price: 15000,
    wasPrice: 19500,
    discountPercent: 23,
    featured: true,
    bestseller: true,
    stock: 30,
    svgRender: '/images/earrings/earrings_cover.jpeg',
    categoryName: 'Earrings',
    categorySlug: 'earrings'
  },
  {
    id: 108,
    name: 'Heritage Gold Necklace',
    slug: 'heritage-gold-necklace',
    description: 'A heavy luxury collar necklace made of hand-woven 22k gold wire links. Perfect statement heirloom.',
    price: 95000,
    wasPrice: 125000,
    discountPercent: 24,
    featured: true,
    bestseller: true,
    stock: 5,
    svgRender: '/images/necklaces/necklaces_cover.jpeg',
    categoryName: 'Necklaces',
    categorySlug: 'necklaces'
  },
  {
    id: 111,
    name: 'Gold Charm Bracelet',
    slug: 'gold-charm-bracelet',
    description: 'A delicate double-link chain in 22k gold holding three iconic VEHA star and crown charms.',
    price: 22000,
    wasPrice: 29500,
    discountPercent: 25,
    featured: true,
    bestseller: false,
    stock: 18,
    svgRender: '/images/bracelets/bracelets_cover.jpeg',
    categoryName: 'Bracelets',
    categorySlug: 'bracelets'
  },
  {
    id: 114,
    name: 'Traditional Gold Bangle',
    slug: 'traditional-gold-bangle',
    description: 'A classic solid gold bangle featuring hand-chiselled patterns of luxury royal designs.',
    price: 48000,
    wasPrice: 62000,
    discountPercent: 22,
    featured: true,
    bestseller: true,
    stock: 15,
    svgRender: '/images/collections/collection_cover.jpeg',
    categoryName: 'Bangles',
    categorySlug: 'bangles'
  },
  {
    id: 102,
    name: 'Eternal Gold Ring',
    slug: 'eternal-gold-ring',
    description: 'An elegant, polished band symbolizing eternal style. Crafted in solid 22k hallmark gold with fine edge detailing.',
    price: 25000,
    wasPrice: 32000,
    discountPercent: 21,
    featured: true,
    bestseller: false,
    stock: 20,
    svgRender: '/images/rings/rings_cover.jpeg',
    categoryName: 'Rings',
    categorySlug: 'rings'
  },
  {
    id: 106,
    name: 'Emerald Luxe Earrings',
    slug: 'emerald-luxe-earrings',
    description: 'Deep forest green natural emerald drops surrounded by a halo of brilliant crystals in 22k gold settings.',
    price: 32000,
    wasPrice: 42000,
    discountPercent: 23,
    featured: true,
    bestseller: false,
    stock: 12,
    svgRender: '/images/earrings/earrings_cover.jpeg',
    categoryName: 'Earrings',
    categorySlug: 'earrings'
  },
  {
    id: 109,
    name: 'Royal Diamond Necklace',
    slug: 'royal-diamond-necklace',
    description: 'An breathtaking cascade of diamonds mounted on a platinum and 22k yellow gold linked collar.',
    price: 145000,
    wasPrice: 195000,
    discountPercent: 25,
    featured: true,
    bestseller: true,
    stock: 3,
    svgRender: '/images/necklaces/necklaces_cover.jpeg',
    categoryName: 'Necklaces',
    categorySlug: 'necklaces'
  },
  {
    id: 112,
    name: 'Diamond Tennis Bracelet',
    slug: 'diamond-tennis-bracelet',
    description: 'A continuous, shimmering row of princess-cut diamonds in a flexible gold claw setting.',
    price: 65000,
    wasPrice: 85000,
    discountPercent: 23,
    featured: true,
    bestseller: true,
    stock: 7,
    svgRender: '/images/bracelets/bracelets_cover.jpeg',
    categoryName: 'Bracelets',
    categorySlug: 'bracelets'
  },
  {
    id: 115,
    name: 'Royal Heritage Bangle',
    slug: 'royal-heritage-bangle',
    description: 'A premium, heavy gold bangle studded with precious gems and finished with traditional gold beads.',
    price: 75000,
    wasPrice: 98000,
    discountPercent: 23,
    featured: true,
    bestseller: false,
    stock: 9,
    svgRender: '/images/collections/collection_cover.jpeg',
    categoryName: 'Bangles',
    categorySlug: 'bangles'
  },
  {
    id: 103,
    name: 'Heritage Solitaire Ring',
    slug: 'heritage-solitaire-ring',
    description: 'A single brilliant-cut heirloom solitaire diamond raised on a slender band of 22k hallmark gold.',
    price: 85000,
    wasPrice: 110000,
    discountPercent: 22,
    featured: true,
    bestseller: true,
    stock: 8,
    svgRender: '/images/rings/rings_cover.jpeg',
    categoryName: 'Rings',
    categorySlug: 'rings'
  },
  {
    id: 107,
    name: 'Royal Chandbali Earrings',
    slug: 'royal-chandbali-earrings',
    description: 'Intricate crescent moon chandeliers finished with fine gold filigree, drop beads, and precious gems.',
    price: 55000,
    wasPrice: 69000,
    discountPercent: 20,
    featured: false,
    bestseller: true,
    stock: 10,
    svgRender: '/images/earrings/earrings_cover.jpeg',
    categoryName: 'Earrings',
    categorySlug: 'earrings'
  },
  {
    id: 110,
    name: 'Signature Pendant Necklace',
    slug: 'signature-pendant-necklace',
    description: 'A minimalist 22k gold chain carrying a sleek, hand-engraved gold disc pendant set with a single crystal.',
    price: 12000,
    wasPrice: 16500,
    discountPercent: 27,
    featured: false,
    bestseller: false,
    stock: 40,
    svgRender: '/images/necklaces/necklaces_cover.jpeg',
    categoryName: 'Necklaces',
    categorySlug: 'necklaces'
  },
  {
    id: 113,
    name: 'Heritage Kada Bracelet',
    slug: 'heritage-kada-bracelet',
    description: 'A thick, solid gold kada bangle-bracelet with carved lion-head ends, inspired by ancient jewelry designs.',
    price: 42000,
    wasPrice: 55000,
    discountPercent: 23,
    featured: false,
    bestseller: false,
    stock: 14,
    svgRender: '/images/bracelets/bracelets_cover.jpeg',
    categoryName: 'Bracelets',
    categorySlug: 'bracelets'
  },
  {
    id: 116,
    name: 'Limited Edition Collection Piece',
    slug: 'limited-edition-collection-piece',
    description: 'An exclusive masterpiece. Double-layered diamonds and gold choker neckpiece from the signature archive.',
    price: 120000,
    wasPrice: 155000,
    discountPercent: 22,
    featured: true,
    bestseller: false,
    stock: 2,
    svgRender: '/images/products/product_detail_hero.jpeg',
    categoryName: 'Necklaces',
    categorySlug: 'necklaces'
  },
  {
    id: 104,
    name: 'Crown Signature Ring',
    slug: 'crown-signature-ring',
    description: 'VEHA house signature ring shaped in a delicate gold crown motif. Embellished with micro-pavé diamonds.',
    price: 18000,
    wasPrice: 24000,
    discountPercent: 25,
    featured: false,
    bestseller: false,
    stock: 25,
    svgRender: '/images/rings/rings_cover.jpeg',
    categoryName: 'Rings',
    categorySlug: 'rings'
  },
  {
    id: 117,
    name: 'Maharani Collection Piece',
    slug: 'maharani-collection-piece',
    description: 'A breathtaking emerald and diamond bib necklace crafted for royalty. Truly magnificent craftsmanship.',
    price: 250000,
    wasPrice: 320000,
    discountPercent: 21,
    featured: true,
    bestseller: true,
    stock: 1,
    svgRender: '/images/products/product_detail_hero.jpeg',
    categoryName: 'Necklaces',
    categorySlug: 'necklaces'
  }
];
